### PR TITLE
Writing improvements to "How to Gracefully Close Channels"

### PR DESCRIPTION
**Pull request by GCrispino**
Hello!
This PR contains some suggestions to improve the writing of this article.

Of course, I'm open to suggestions 🙂 

By the way, congratulations on the article, it's really good 👏🏼

### CODE REVIEW

**Review by go101 — APPROVED** [review]
@GCrispino 
Many thanks for these improvements!

**Comment by GCrispino** [comment]
@go101 thanks for accepting it!

**Comment by go101** [comment]
My English is very not decent. :D
Your improvements make this article much better than before. :)

Many thanks!

**Comment by GCrispino** [comment]
No, it's pretty good!
Happy to have helped!

**Pull request merged**
