### PR TITLE
support go mod

### PR DESCRIPTION
**Pull request by paulyung541**

### CODE REVIEW

**Comment by go101** [comment]
Hi @paulyung541,
Thanks for this PR.

I am also considering to let this project support go modules.
But I also hesitate for I haven't found a significant benefit for this change.
What are the benefits of supporting Go modules do you think?

**Comment by paulyung541** [comment]
many gays use the go version > 1.11 and set GO111MODULE=on. most of the time i don't need clone the go project in GOPATH because go mod. if don't set go mod, i can't run the server with command `go run .`, it will report the error like follow.
```bash
go: cannot find main module, but found .git/config in 
$GOPATH/src/github.com/go101/go101
	to create a module there, run:
	go mod init
``` 
Otherwise, if merge this pr, it won't affect the people who use go version < 1.11. They can use it like before.

**Comment by paulyung541** [comment]
Many gays use the go version > 1.11 and set GO111MODULE=on. Most of the time i don't need clone the go project in GOPATH because go mod. If don't set go mod, i can't run the server with command `go run .`, it will report the error like follow.
```bash
go: cannot find main module, but found .git/config in 
$GOPATH/src/github.com/go101/go101
	to create a module there, run:
	go mod init
```
Otherwise, if merge this pr, it won't affect the people who use go version < 1.11. They can use it like before.

**Comment by TapirLiu** [comment]
Thanks for the feedback. It looks the fact you mentioned is true.
This should be a flaw of the Go modules feature implementation.

Ok, I will merge this PR. Thanks very much!

BTW, is the `gay` typo? Should it be `guy`? ;D

**Comment by go101** [comment]
@paulyung541 I forgot to mention that it would be best to set the GO111MODULE env as auto now to avoid all kinds of weird problems.

**Pull request merged**
